"""Packs 256 px UI art cells into 1024 x 1024 sheets and writes the Luau data modules (system Python + Pillow).

  python tools/ui/atlas.py portraits      # art/portraits/<form>.png -> upload/portraits_<n>.png + UI/Art/Portraits.luau
  python tools/ui/atlas.py icons          # art/ui/icons/cells/<name>.png -> upload/icons_<n>.png + UI/Art/Icons.luau
  python tools/ui/atlas.py template       # art/ui/upload/ids.json: every upload file -> "" (fill in, then `ids`)
  python tools/ui/atlas.py ids <ids.json> # write uploaded asset ids into the modules (and Theme.Images)

portraits keeps only forms that exist in this branch's src/shared/Config/Species.luau (the art folder
can hold forms from unmerged branches); icons keeps every built cell that still has a row in
art/ui/ICONS.md. Cells are packed 4 x 4 per sheet in a stable order (sorted by name), so re-running
after a merge only moves art when a new name sorts in. Sheets go to art/ui/upload/ (git-ignored:
upload them, do not commit them); manifests go to art/ui/<kind>.json and a 64 px review sheet to
art/ui/<kind>_contact.jpg.

A re-run keeps the asset id of every sheet whose pixels did not change (the manifest remembers each
sheet's hash and id) and clears the id of a sheet that did, so the game falls back to the procedural
drawing for those cells instead of showing the wrong picture.

ids.json maps an uploaded file name to its asset id, e.g.
  {"portraits_1.png": 1234567890, "icons_1.png": "rbxassetid://1234567891", "panel.png": 123, "button.png": 124}
panel.png / button.png go to Theme.Images.PanelTexture / ButtonTexture. Empty values are skipped.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import uiart  # noqa: E402

CELL, SHEET = 256, 1024
PER_ROW = SHEET // CELL
PER_SHEET = PER_ROW * PER_ROW
THEME = uiart.ROOT / "src" / "client" / "UI" / "Theme.luau"
THEME_KEYS = {"panel.png": "PanelTexture", "button.png": "ButtonTexture"}

KINDS = {
    "portraits": {
        "module": "Portraits",
        "key": "Cells",
        "what": "Monster portraits",
        "made": "Rendered by tools/ui/portraits.py from the rigged models.",
        "lookup": "formId",
    },
    "icons": {
        "module": "Icons",
        "key": "Cells",
        "what": "Item and currency icons",
        "made": "Generated by tools/ui/codex_icons.py from art/ui/ICONS.md.",
        "lookup": "icon name (`cur_coin`, `decor_hay_bale`, `acc_top_hat`, ...)",
    },
}


def asset_id(v) -> str:
    s = str(v).strip()
    return s if s.startswith("rbxassetid://") else f"rbxassetid://{int(s)}"


def cells_for(kind: str) -> dict[str, Path]:
    if kind == "portraits":
        folder = uiart.ROOT / "art" / "portraits"
        want = [f["id"] for f in uiart.config()["forms"]]
    else:
        folder = uiart.ART_UI / "icons" / "cells"
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        import codex_icons

        want = list(codex_icons.load_spec())
    return {n: folder / f"{n}.png" for n in sorted(set(want)) if (folder / f"{n}.png").exists()}


def luau_module(kind: str, sheets: list[dict], rects: dict[str, tuple[int, int, int]]) -> str:
    k = KINDS[kind]
    lines = [
        "--[[",
        f"\t{k['what']}: 256 px cells packed on 1024 px sheets. {k['made']}",
        f"\tGENERATED by `python tools/ui/atlas.py {kind}`: do not edit by hand. `python tools/ui/atlas.py ids <json>`",
        "\twrites the uploaded sheet ids. A sheet id of \"\" means not uploaded yet: callers keep their procedural drawing.",
        "",
        f"\t{k['key']}[{k['lookup'].split(' ')[0]}] = {{ sheet, x, y }} (pixel offset of the cell on that sheet).",
        "\tRead it through UI/Art/Sheet (`Sheet.portrait`, `Sheet.icon`, `Sheet.find`).",
        "]]",
        "",
        f"local {k['module']} = {{}}",
        "",
        f"{k['module']}.Cell = {CELL}",
        "",
        f"{k['module']}.Sheets = {{",
    ]
    for s in sheets:
        lines.append(f"\t\"{s['id']}\", -- {s['file']}")
    lines += ["}", "", f"{k['module']}.{k['key']} = {{"]
    for n in sorted(rects):
        si, x, y = rects[n]
        key = n if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", n) else f'["{n}"]'
        lines.append(f"\t{key} = {{ {si}, {x}, {y} }},")
    lines += ["}", "", f"return {k['module']}", ""]
    return "\n".join(lines)


def cmd_pack(kind: str) -> None:
    cells = cells_for(kind)
    if not cells:
        sys.exit(f"no {kind} cells found; render / build them first")
    uiart.UPLOAD.mkdir(parents=True, exist_ok=True)
    man_path = uiart.ART_UI / f"{kind}.json"
    old = json.loads(man_path.read_text(encoding="utf-8")) if man_path.exists() else {"sheets": []}
    old_ids = {s["file"]: (s["hash"], s["id"]) for s in old["sheets"]}
    for stale in uiart.UPLOAD.glob(f"{kind}_*.png"):
        stale.unlink()
    names = list(cells)
    sheets, rects = [], {}
    for si in range(0, len(names), PER_SHEET):
        sheet = Image.new("RGBA", (SHEET, SHEET), (0, 0, 0, 0))
        chunk = names[si:si + PER_SHEET]
        idx = si // PER_SHEET + 1
        for ci, n in enumerate(chunk):
            im = Image.open(cells[n]).convert("RGBA")
            if im.size != (CELL, CELL):
                im = im.resize((CELL, CELL), Image.LANCZOS)
            x, y = (ci % PER_ROW) * CELL, (ci // PER_ROW) * CELL
            sheet.paste(im, (x, y))
            rects[n] = (idx, x, y)
        file = f"{kind}_{idx}.png"
        sheet.save(uiart.UPLOAD / file, optimize=True)
        digest = hashlib.sha1(sheet.tobytes()).hexdigest()[:16]
        prev = old_ids.get(file)
        keep = prev[1] if prev and prev[0] == digest else ""
        sheets.append({"file": file, "hash": digest, "id": keep, "cells": chunk})
    man_path.write_text(json.dumps({"cell": CELL, "sheet": SHEET, "sheets": sheets}, indent=1), encoding="utf-8", newline="\n")
    uiart.LUAU_ART.mkdir(parents=True, exist_ok=True)
    mod = uiart.LUAU_ART / f"{KINDS[kind]['module']}.luau"
    mod.write_text(luau_module(kind, sheets, rects), encoding="utf-8", newline="\n")
    contact(cells, uiart.ART_UI / f"{kind}_contact.jpg")
    kept = sum(1 for s in sheets if s["id"])
    print(f"{kind}: {len(rects)} cells on {len(sheets)} sheets -> {uiart.UPLOAD} ({kept} sheet ids kept); wrote {mod.name}")


def contact(cells: dict[str, Path], out: Path, px: int = 64, per_row: int = 16) -> None:
    """A small review sheet (committed): every cell at 64 px on the panel cream."""
    names = list(cells)
    rows = (len(names) + per_row - 1) // per_row
    sheet = Image.new("RGBA", (per_row * px, rows * px), "#FFF7E3")
    for i, n in enumerate(names):
        im = Image.open(cells[n]).convert("RGBA").resize((px, px), Image.LANCZOS)
        sheet.alpha_composite(im, ((i % per_row) * px, (i // per_row) * px))
    sheet.convert("RGB").save(out, quality=85)


def cmd_ids(path: Path) -> None:
    ids = {k: asset_id(v) for k, v in json.loads(path.read_text(encoding="utf-8")).items() if str(v).strip()}
    used = set()
    for kind in KINDS:
        man_path = uiart.ART_UI / f"{kind}.json"
        if not man_path.exists():
            continue
        man = json.loads(man_path.read_text(encoding="utf-8"))
        for s in man["sheets"]:
            if s["file"] in ids:
                s["id"] = ids[s["file"]]
                used.add(s["file"])
        man_path.write_text(json.dumps(man, indent=1), encoding="utf-8", newline="\n")
        rects = {n: (i + 1, (ci % PER_ROW) * CELL, (ci // PER_ROW) * CELL)
                 for i, s in enumerate(man["sheets"]) for ci, n in enumerate(s["cells"])}
        (uiart.LUAU_ART / f"{KINDS[kind]['module']}.luau").write_text(luau_module(kind, man["sheets"], rects),
                                                                       encoding="utf-8", newline="\n")
    theme = THEME.read_text(encoding="utf-8")
    for file, key in THEME_KEYS.items():
        if file in ids:
            theme, n = re.subn(rf'(\n\t{key} = )"[^"]*"', rf'\g<1>"{ids[file]}"', theme)
            if n != 1:
                sys.exit(f"Theme.Images.{key} not found in {THEME}")
            used.add(file)
    THEME.write_text(theme, encoding="utf-8", newline="\n")
    unknown = sorted(set(ids) - used)
    print(f"wrote {len(used)} ids" + (f"; unknown files (ignored): {', '.join(unknown)}" if unknown else ""))


def cmd_template() -> None:
    out = uiart.UPLOAD / "ids.json"
    old = json.loads(out.read_text(encoding="utf-8")) if out.exists() else {}
    files = sorted((p.name for p in uiart.UPLOAD.glob("*.png")), key=lambda n: (re.sub(r"\d+", "", n), len(n), n))
    out.write_text(json.dumps({f: old.get(f, "") for f in files}, indent=1), encoding="utf-8", newline="\n")
    print(f"wrote {out} ({len(files)} files)")


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in ("portraits", "icons", "ids", "template"):
        sys.exit(__doc__)
    if sys.argv[1] == "template":
        cmd_template()
    elif sys.argv[1] == "ids":
        cmd_ids(Path(sys.argv[2]))
    else:
        cmd_pack(sys.argv[1])


if __name__ == "__main__":
    main()
