"""The clip data a rig's module carries, shared by export_roblox.py (a fresh rig) and add_clips.py
(new clips on a rig already in the game). Runs inside Blender.

A form has two modules. MeshMonsters/<form>.luau holds the bounds, the bones and the first three
clips (idle, walk, hop, at 30 fps); its bones live in the published mesh asset, so it changes only
with a re-rig and a re-publish. MeshMonsterClips/<form>.luau holds the EXTRA clips (riglib.EXTRA:
sleep, eat, cheer, cheer2, attack, hurt, faint, sit, trick, at 10-15 fps) for the same bones in the
same order. Two modules because Studio refuses a Source of 200,000 characters or more: the largest
first module is 78 KB, and the extra clips take about as much again.

Clip data is f32 x7 per bone per frame (qx, qy, qz, qw, tx, ty, tz): each bone's pose in its own
rest frame (Bone.Transform), base64 wrapped at 128 columns inside a long string.
"""

import base64
import re
import struct

import bpy

BASE = ("idle", "walk", "hop")  # the clips in MeshMonsters/<form>.luau
MAX_SOURCE = 190_000  # Studio refuses a Source of 200,000 characters or more


def b64(fmt: str, values) -> str:
    raw = base64.b64encode(struct.pack("<" + fmt * (len(values) // len(fmt)), *values)).decode()
    return "\n".join(raw[i : i + 128] for i in range(0, len(raw), 128))


def bone_lines(arm) -> list:
    """The module's bones table, one line a bone (Roblox axes, mesh space), exactly as
    export_roblox.py has always written it."""
    from mathutils import Matrix

    c4 = Matrix(((-1, 0, 0), (0, 0, 1), (0, 1, 0))).to_4x4()
    bones = list(arm.data.bones)
    index = {b.name: i for i, b in enumerate(bones)}
    lines = []
    for b in bones:
        m = c4 @ arm.matrix_world @ b.matrix_local
        t, q = m.to_translation(), m.to_quaternion()
        parent = index[b.parent.name] + 1 if b.parent else 0
        lines.append(
            f'\t\t{{ name = "{b.name}", parent = {parent}, deform = {str(b.use_deform).lower()}, '
            f"cframe = {{ {t.x:.5f}, {t.y:.5f}, {t.z:.5f}, {q.x:.6f}, {q.y:.6f}, {q.z:.6f}, {q.w:.6f} }} }},"
        )
    return lines


def sample(arm, action) -> tuple:
    """(frames, data): every frame of the action, each bone's pose in its own rest frame. Every
    pose bone is put back to rest first, so a channel the action does not key never carries a value
    over from the clip sampled before it."""
    for pb in arm.pose.bones:
        pb.location = (0, 0, 0)
        pb.rotation_quaternion = (1, 0, 0, 0)
    arm.animation_data.action = action
    scene = bpy.context.scene
    start, end = (int(x) for x in action.frame_range)
    data = []
    for f in range(start, end + 1):
        scene.frame_set(f)
        for b in arm.data.bones:
            loc, rot, _ = arm.pose.bones[b.name].matrix_basis.decompose()
            data += [rot.x, rot.y, rot.z, rot.w, loc.x, loc.y, loc.z]
    return end - start + 1, data


def clip_line(name: str, fps: int, frames: int, data) -> str:
    return f"\t\t{name} = {{ fps = {fps}, frames = {frames}, data = [[\n{b64('f', data)}\n]] }},"


def extra_actions(extra_names) -> list:
    return [bpy.data.actions[name] for name in extra_names if name in bpy.data.actions]


def extras_module(form: str, arm, names) -> str:
    """MeshMonsterClips/<form>.luau for the extra actions (named in riglib.EXTRA order), or ""
    when the rig has none."""
    lines = []
    for action in extra_actions(names):
        frames, data = sample(arm, action)
        lines.append(clip_line(action.name, int(action.get("fps", bpy.context.scene.render.fps)), frames, data))
    if not lines:
        return ""
    text = f"""--[[
	{form}: the extra clips, generated by tools/blender (add_clips.py or export_roblox.py) from
	art/rigs/{form}/rig.blend. Do not edit. MeshMonster adds them to MeshMonsters/{form}'s clips: same
	bones in the same order ({len(arm.data.bones)}), so they need no re-published mesh.
]]

return {{
	form = "{form}",
	bones = {len(arm.data.bones)},
	clips = {{
{chr(10).join(lines)}
	}},
}}
"""
    if len(text) >= MAX_SOURCE:
        raise SystemExit(f"MeshMonsterClips/{form}.luau is {len(text)} characters: over Studio's Source cap")
    return text


# ─── Proving a module unchanged ─────────────────────────────────────────────────────────

BONE = re.compile(r'name = "([^"]+)",\s*parent = (\d+),\s*deform = (\w+),\s*cframe = \{\s*([^}]*?),?\s*\}')
CLIP = re.compile(r"(\w+) = \{\s*fps = (\d+),\s*frames = (\d+),\s*data = \[\[(.*?)\]\],?\s*\}", re.S)


def bone_fields(text: str) -> list:
    """(name, parent, deform, cframe numbers as written) per bone: stylua spreads a bone over
    several lines when its line would pass 140 columns, so the fields are compared, as text."""
    return [(m[1], m[2], m[3], re.sub(r"\s+", " ", m[4])) for m in BONE.finditer(text)]


def module_parts(text: str) -> tuple:
    """(bone fields, {clip: (fps, frames, base64)}) read back from a module."""
    bones = bone_fields(text.split("clips = {", 1)[0])
    clips = {m[1]: (int(m[2]), int(m[3]), re.sub(r"\s", "", m[4])) for m in CLIP.finditer(text)}
    return bones, clips


def prove_unchanged(arm, text: str, form: str) -> str:
    """Raises SystemExit unless the rig's bones and its idle, walk and hop, sampled again, are
    byte for byte what the game's module holds. Returns a one-line summary."""
    bones, clips = module_parts(text)
    mine = bone_fields("\n".join(bone_lines(arm)))
    if mine != bones:
        diff = next((i for i, (a, b) in enumerate(zip(mine, bones)) if a != b), min(len(mine), len(bones)))
        raise SystemExit(f"{form}: the rig's bones differ from the module's at bone {diff + 1} ({len(mine)} vs {len(bones)} bones)")
    for name in BASE:
        if name not in clips:
            raise SystemExit(f"{form}: the module has no {name} clip")
        frames, data = sample(arm, bpy.data.actions[name])
        fps = bpy.context.scene.render.fps
        got = (fps, frames, b64("f", data).replace("\n", ""))
        if got != clips[name]:
            raise SystemExit(f"{form}: the rig's {name} clip differs from the module's")
    return f"{len(bones)} bones and {', '.join(BASE)} identical to the module"
